### ISSUE TITLE
iOS Side User is not register Once entering to wss or ws Server URL and Token for LiveKit 

### ISSUE THREAD

**Issue by viv578ek** [livekit/client-sdk-swift#210] opened 2023-05-16 10:19 UTC
**Describe the bug**
**Setup to Web Portel** 

server bind -> livekit-server --dev --bind 0.0.0.0
Domain Name : X.X.X.X
Generate token -> 
livekit-cli create-token --api-key devkey --api-secret secret --join --room Test_room --identity demo_01  --valid-for 24h
after generate token he will be not connect ws://XXX.XXX.XX.XX:7880 and wss://XXX.XXX.XX.XX:7880
we are created ssl certificate (.crt and .pem )

**iOS Setup** 
We have  server for LiveKit and Getting ws or wss server URL Like : - and Token - 

After that I have clone the code from -  https://github.com/livekit/client-sdk-swift and fallow the step setup in iOS side 
Enter the WSS server And Token Getting error :-

debug LiveKitSDK : [] WebSocket.cleanUp(reason:notify:) reason: Optional(LiveKit.DisconnectReason.networkError(NetworkError.disconnected WebSocket disconnected rawError: An SSL error has occurred and a secure connection to the server cannot be made.))

**Note: Socket is not connected iOS side Only and Android side Still Connected but after some time close the connection till 10-12 seconds **

**SDK Version**

iOS : 1.0.26
Web Setup : v1.2.5

**iOS/macOS Version**
iOS : 16.4.2
MacOS : 13.3.1

**Steps to Reproduce**
Unable to Connect after enter the wss server and token  

**Expected behavior**
Socket Connection need to be Connect Still Not Yet getting error 
**Error**
2023-05-15T14:36:11+0530 debug LiveKitSDK : [] WebSocket.cleanUp(reason:notify:) reason: Optional(LiveKit.DisconnectReason.networkError(NetworkError.disconnected WebSocket disconnected rawError: An SSL error has occurred and a secure connection to the server cannot be made.))

Please help me if Any one have any idea.

**Comment by ParthLotia** [comment] 2023-05-16 10:22
Yes I am facing the exact same issue. If you find any solution please share with me as well.

**Comment by YashSopariya** [comment] 2023-05-16 11:29
yes , we had follow all above steps for setup server in Go Language. and from Android side we have used LiveKitSDK and checked the demo. in that demo we are facing connection closed when room is active. automatic connection closed of the room after 20-30 seconds.

**Comment by hiroshihorie** [comment] 2023-05-16 12:05
Hello do you mean you cannot connect to your own LiveKit server ?

**Comment by viv578ek** [comment] 2023-05-16 12:06
Yes

**Comment by viv578ek** [comment] 2023-05-16 12:13
I have tried only latest version and not success

**Comment by hiroshihorie** [comment] 2023-05-16 12:16
Can you try unsecure connection with url starting `ws://.....`

**Comment by viv578ek** [comment] 2023-05-16 12:28
We have tried both ws://..... and wss://......  

For wss://..... we need to SSL certificate that is also done from server side

**Comment by Ankit0899** [comment] 2023-05-17 09:53
Yes, I am facing the exact same issue in Android And IOS. If you find any solution please share with me as well.

**Comment by hiroshihorie** [comment] 2023-05-17 10:03
You see this issue with Android SDK also ? Can you try reporting this in our community slack ?

**Comment by YashSopariya** [comment] 2023-05-17 10:10
@hiroshihorie in android SDK room connection is works fine but the problem is after room joined in android it will disconnect automatically after 20-30 seconds.

in an iOS only we are facing connection issue.

**Comment by viv578ek** [comment] 2023-05-18 09:44
Any update ?

**Comment by viv578ek** [comment] 2023-05-22 06:03
Hello All 

    If any one update regarding above query please revert me I am stuck form my side.

Thanks

**Comment by hiroshihorie** [comment] 2023-05-22 06:05
Hi, I'm not sure what's going on, I can reproduce this. Can you try with JS SDK if you can connect to the server ?
I think you can try : https://meet.livekit.io/?tab=custom with your server, does it connect ?.

**Comment by viv578ek** [comment] 2023-05-22 06:19
Thanks for replaying Let me check and revert you

**Comment by viv578ek** [comment] 2023-05-22 09:45
Hello @hiroshihorie 

   Can we connect a short call for try to fixed issue. Where we actually stuck. 
  If you fine to connect we can connect  in Skype - viv578ek@gmail.com

**Comment by hiroshihorie** [comment] 2023-05-28 18:04
Hi can you simply try https://meet.livekit.io/?tab=custom to see if your server is set up correctly ?
Just to confirm, you are not using LiveKit Cloud and you are using your own server ?

**Comment by viv578ek** [comment] 2023-05-29 09:54
@hiroshihorie  Thanks for support  No we got success with  LiveKit Cloud server every thing working fine 

you can close the ticket 

Thanks for support

**Comment by hiroshihorie** [comment] 2023-05-29 09:56
Sounds like your server setup issue. I will close this.

**Closed** 2023-05-29 09:57 UTC
Labels: bug
