### ISSUE TITLE
Screenshare audio for IOS sdk

### ISSUE THREAD

**Issue by royatanu94** [livekit/client-sdk-swift#417] opened 2024-06-27 10:07 UTC
**Is your feature request related to a problem? Please describe.**
Currently IOS app does not support the audio of shared screen.

**Describe the solution you'd like**
IOS app should support screenshare audio like web sdk has.

**Describe alternatives you've considered**

**Additional context**

**Comment by hiroshihorie** [comment] 2024-07-01 17:20
Hi, unfortunately this is not supported at the moment .
I would definitely like to implement this.

**Comment by hiroshihorie** [comment] 2024-07-01 17:23
This is related / duplicate of https://github.com/livekit/client-sdk-swift/issues/385
I will close this one.

**Closed by hiroshihorie** 2024-07-01 17:23 UTC
Labels: duplicate, enhancement
