### ISSUE TITLE
When "Portait Locked" option is activated, VideoView behaves wrong

### ISSUE THREAD

**Issue by joaomurta** [livekit/client-sdk-swift#146] opened 2022-10-14 19:35 UTC
these are the test steps I did demonstrated in the video:
Remembering that the view controller is locked in landscape, which is supposed to be.

1. I'm in landscape without "Portait Locked"
2. I turn on the camera
3. Rotate iPhone to Portait (physically)
4. I run back to Landscape
5. Turn off camera( we have an observer to turn off the camera when we go to “Control Panel”)
6. Enable “Portait Locked” option
7. I turn on the camera (I'm physically in landscape with “Portait Locked”), and the camera appears like this, with rotation
8. Rotate iPhone to Portait (physically)
9. I run back to Landscape

If you can solve the problem as soon as possible, I would really appreciate it, in fact it is something urgent for me. Thanks and keep up the good work.

https://user-images.githubusercontent.com/24411127/195927883-f55c335d-12dc-4345-b08f-f72f0e867b5b.mov

**Comment by hiroshihorie** [comment] 2022-10-16 12:46
Hello I will try to replicate this one.

**Comment by hiroshihorie** [comment] 2022-10-17 12:11
Hi I did a quick check and it seems to be working as expected . Can you explain more details or can you upload example code to reproduce the issue ?

**Comment by joaomurta** [comment] 2022-10-17 17:29
`    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        .landscape
    }
    
    override var shouldAutorotate: Bool {
        true
    }
    `

what happens is that when we have the "portrait Locked" the camera is rotated as you can see. Videoview behaves like portrait.

https://user-images.githubusercontent.com/24411127/196243735-9655dc68-adc2-44ea-888b-09fe891ed444.mov

**Comment by hiroshihorie** [comment] 2022-10-20 06:51
It seems like a bug but I'm unable to reproduce this at the moment.

**Comment by joaomurta** [comment] 2022-10-27 15:22
Hi @hiroshihorie , first of all, thanks for reply.

I think it's a good approach, as soon as the fix is available can you notify me here in the ticket please?

**Comment by inflamesonly** [comment] 2023-07-19 14:40
do you remember about it?
There is the same problem. The app only has a horizontal view and the camera is not working properly. It would be nice to rotate the picture for sending.

**Comment by hiroshihorie** [comment] 2023-09-12 06:55
Hi, sorry for taking so long but this patch should fix it :
https://github.com/webrtc-sdk/webrtc/pull/92

It will be in the new release. Please re-open if you still see issues.

**Closed by hiroshihorie** 2023-09-12 06:55 UTC
