### ISSUE TITLE
There is no sound after the video connection between iOS is successful

### ISSUE THREAD

**Issue by lifeng-Lee** [livekit/client-sdk-swift#175] opened 2023-01-13 10:16 UTC
Hello LiveKit Team,
I am using the version "1.0.8" SDK source code, when the two iphones are connected to each other, they can hear each other talking at the beginning, but the sound disappears between 30 seconds and one minute after the video connection I can't hear the other party's speech, and the microphone-related permissions are confirmed to be turned on in the phone settings. When the sound disappears, print the data returned by room(_ room: Room, didUpdate speakers: [Participant]) and you will find that speakers.count becomes 0. It is strange that everything is normal with sound at the beginning, and then the call is basically in one session. Within minutes, the other party's voice was no longer heard, and this problem persisted after repeated attempts. And I made sure that the network status is good, because there is no problem with the display of the video screen. There is no sound when switching the mute state through self?.room.localParticipant?.setMicrophone(enabled: ). I don't know where the problem is, hope you can help me.

**Comment by lifeng-Lee** [comment] 2023-01-13 10:22
This is the code for room initialization.

var room = Room(
          delegate: self,
          roomOptions: RoomOptions(
            defaultCameraCaptureOptions: CameraCaptureOptions(
              position: .front,
              dimensions: .h720_169,
              fps: 30
            ),
            defaultAudioCaptureOptions: AudioCaptureOptions(
              echoCancellation: true,
              noiseSuppression: true,
              autoGainControl: true,
              typingNoiseDetection: true,
              highpassFilter: true
            ),
            defaultVideoPublishOptions: VideoPublishOptions(
              encoding: VideoEncoding(
                maxBitrate: 1_500_000,
                maxFps: 30
              ),
              simulcastLayers: [
                VideoParameters.presetH180_169,
                VideoParameters.presetH360_169,
              ]
            ),
            defaultAudioPublishOptions: AudioPublishOptions(
              dtx: true
            ),
            adaptiveStream: true,
            dynacast: true
          )
        )
        self.room = room

        print("token---------\(token)")
        room.connect(url, token).then { room in
            print("RoomDelegate--closure")
            room.localParticipant?.setCamera(enabled: true)
            room.localParticipant?.setMicrophone(enabled: true)
            self.cameraEnable = true
        }.catch { error in
            // failed to connect
            print(error.localizedDescription)
        }

**Comment by hiroshihorie** [comment] 2023-01-13 15:21
Hi, are you using LiveKit Cloud or your own LiveKit server ?

**Comment by hiroshihorie** [comment] 2023-01-16 03:35
I am not able to reproduce this one.

**Comment by lifeng-Lee** [comment] 2023-01-18 06:33
I removed the two parameters defaultAudioCaptureOptions and defaultAudioPublishOptions from RoomOptions, and then carried out the video test and found that there was no problem. Thank you very much for your help.

**Comment by hiroshihorie** [comment] 2023-01-18 08:52
Hi @lifeng-Lee , I'm glad that worked for you.
Still interesting why it didn't work when you passed the options.

I will close this for now.

**Closed by hiroshihorie** 2023-01-18 08:52 UTC
